version: 2

jobs:
    build:
      docker:
        - image: circleci/golang:1.9.7
        - image: circleci/golang:1.10.3
      working_directory: /go/src/github.com/tietang/props

      steps:
        - checkout
        - run: |
            mkdir -p /tmp/output/.props/bin
            wget https://releases.hashicorp.com/consul/0.9.3/consul_0.9.3_linux_amd64.zip?_ga=2.214371295.97069421.1504961822-580552568.1501916240
            unzip consul_0.9.3_linux_amd64* -d consul
            wget https://github.com/coreos/etcd/releases/download/v3.2.9/etcd-v3.2.9-linux-amd64.tar.gz
            tar -zxvf etcd-v3.2.9-linux-amd64.tar.gz
            mv ./etcd-v3.2.9-linux-amd64/etcd /tmp/output/.props/bin
            pwd
            ls /tmp/output/.props/bin
            export PATH=`pwd`:$PATH
            echo $PATH
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
        - run: |
            go test -i -v -race ./...
            go test ./... -covermode=atomic -coverprofile=coverage.txt