version: 2

jobs:
    build:
      docker:
        - image: circleci/golang:1.12.3
      working_directory: /go/src/github.com/tietang/props

      steps:
        - checkout
        - run: |
            sudo apt-get install openjdk-8-jre
            mkdir -p bin
            tar -zxvf server-jre-8u171-linux-x64.tar.gz
            wget https://releases.hashicorp.com/consul/1.4.4/consul_1.4.4_linux_amd64.zip
            unzip consul_1.4.4_linux_amd64.zip  -d ./bin/
            wget https://github.com/coreos/etcd/releases/download/v3.3.8/etcd-v3.3.8-linux-amd64.tar.gz
            tar -zxvf etcd-v3.3.8-linux-amd64.tar.gz
            mv ./etcd-v3.3.8-linux-amd64/etcd ./bin
            pwd
            ls ./bin
            export PATH=`pwd`/jdk1.8.0_171/bin:`pwd`/bin:`pwd`:$PATH
            echo $PATH
            java -version
            go get -u github.com/golang/dep/cmd/dep
            dep ensure
            dep ensure -update
            pwd
            go test -race ./... -covermode atomic -coverprofile=coverage.txt