version: 2

jobs:
    build:

dependencies:
  pre:
    - wget https://releases.hashicorp.com/consul/0.9.3/consul_0.9.3_linux_amd64.zip?_ga=2.214371295.97069421.1504961822-580552568.1501916240
    - unzip consul_0.9.3_linux_amd64* -d ~/.local/bin
    - wget https://github.com/coreos/etcd/releases/download/v3.2.9/etcd-v3.2.9-linux-amd64.tar.gz
    - tar -zxvf etcd-v3.2.9-linux-amd64.tar.gz
    - mv ./etcd-v3.2.9-linux-amd64/etcd ~/.local/bin
    - pwd
#    - cp consul/consul `pwd`/.local/bin
    - ls ~/.local/bin
    - export PATH=`pwd`:$PATH
    - echo $PATH
    - go get github.com/ArthurHlt/gominlog
    - go get github.com/tietang/go-utils
    - go get github.com/sirupsen/logrus
    - go get gopkg.in/yaml.v2
    - go get github.com/tietang/props
    - go get github.com/smartystreets/goconvey/convey
    - go get -u github.com/tietang/go-eureka-client/eureka/config